// Autogenerated from Pigeon (v1.0.10), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "analytics.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}

@interface FLTVersion ()
+ (FLTVersion *)fromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation FLTVersion
+ (FLTVersion *)fromMap:(NSDictionary *)dict {
  FLTVersion *result = [[FLTVersion alloc] init];
  result.string = dict[@"string"];
  if ((NSNull *)result.string == [NSNull null]) {
    result.string = nil;
  }
  return result;
}
- (NSDictionary *)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.string ? self.string : [NSNull null]), @"string", nil];
}
@end

@interface FLTExampleApiCodecReader : FlutterStandardReader
@end
@implementation FLTExampleApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [FLTVersion fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface FLTExampleApiCodecWriter : FlutterStandardWriter
@end
@implementation FLTExampleApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[FLTVersion class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface FLTExampleApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FLTExampleApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FLTExampleApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FLTExampleApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FLTExampleApiGetCodec() {
  static dispatch_once_t s_pred = 0;
  static FlutterStandardMessageCodec *s_sharedObject = nil;
  dispatch_once(&s_pred, ^{
    FLTExampleApiCodecReaderWriter *readerWriter = [[FLTExampleApiCodecReaderWriter alloc] init];
    s_sharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return s_sharedObject;
}


void FLTExampleApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTExampleApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.ExampleApi.getPlatformVersion"
        binaryMessenger:binaryMessenger
        codec:FLTExampleApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getPlatformVersionWithError:)], @"FLTExampleApi api (%@) doesn't respond to @selector(getPlatformVersionWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        FLTVersion *output = [api getPlatformVersionWithError:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface FLTAnalyticsApiCodecReader : FlutterStandardReader
@end
@implementation FLTAnalyticsApiCodecReader
@end

@interface FLTAnalyticsApiCodecWriter : FlutterStandardWriter
@end
@implementation FLTAnalyticsApiCodecWriter
@end

@interface FLTAnalyticsApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FLTAnalyticsApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FLTAnalyticsApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FLTAnalyticsApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FLTAnalyticsApiGetCodec() {
  static dispatch_once_t s_pred = 0;
  static FlutterStandardMessageCodec *s_sharedObject = nil;
  dispatch_once(&s_pred, ^{
    FLTAnalyticsApiCodecReaderWriter *readerWriter = [[FLTAnalyticsApiCodecReaderWriter alloc] init];
    s_sharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return s_sharedObject;
}


void FLTAnalyticsApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTAnalyticsApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.AnalyticsApi.sendScreenView"
        binaryMessenger:binaryMessenger
        codec:FLTAnalyticsApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(sendScreenViewEventName:error:)], @"FLTAnalyticsApi api (%@) doesn't respond to @selector(sendScreenViewEventName:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_eventName = args[0];
        FlutterError *error;
        [api sendScreenViewEventName:arg_eventName error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.AnalyticsApi.sendInteraction"
        binaryMessenger:binaryMessenger
        codec:FLTAnalyticsApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(sendInteractionCategory:action:label:error:)], @"FLTAnalyticsApi api (%@) doesn't respond to @selector(sendInteractionCategory:action:label:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_category = args[0];
        NSString *arg_action = args[1];
        NSString *arg_label = args[2];
        FlutterError *error;
        [api sendInteractionCategory:arg_category action:arg_action label:arg_label error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
