# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

workspace 'App.xcworkspace'
project 'App.xcodeproj'
project 'Modules/Journey/Chip/Chip.xcodeproj'
project 'Modules/Journey/Home/Home.xcodeproj'
project 'Modules/Journey/Login/Login.xcodeproj'
project 'Modules/Journey/Profile/Profile.xcodeproj'

############## Base modules ##############

def networking
  pod 'Networking', :path => 'Modules/Structural/Networking/Networking.podspec'
end

def networking_interfaces
  pod 'NetworkingInterfaces', :path => 'Modules/Structural/Networking/NetworkingInterfaces.podspec'
end

def analytics
  pod 'Analytics', :path => 'Modules/Structural/Analytics/Analytics.podspec'
end

def analytics_interfaces
  pod 'AnalyticsInterfaces', :path => 'Modules/Structural/Analytics/AnalyticsInterfaces.podspec'
end

def appsecurity
  pod 'AppSecurity', :path => 'Modules/Structural/AppSecurity/AppSecurity.podspec'
end

def appsecurity_interfaces
  pod 'AppSecurityInterfaces', :path => 'Modules/Structural/AppSecurity/AppSecurityInterfaces.podspec'
end

def core
  pod 'Core', :path => 'Modules/Structural/Core/Core.podspec'
end
  
############## Journey modules ##############

def chip
  pod 'Chip', :path => 'Modules/Journey/Chip/Chip.podspec'
end

def login
  pod 'Login', :path => 'Modules/Journey/Login/Login.podspec'
end

def profile
  pod 'Profile', :path => 'Modules/Journey/Profile/Profile.podspec'
end

def home
  pod 'Home', :path => 'Modules/Journey/Home/Home.podspec'
end

############## Journey Targets ##############

target 'App' do
  # Comment the next line if you don't want to use dynamic frameworks
  project 'App.xcodeproj'
  use_frameworks!

  # Pods for App
  home
  profile
  login
  chip
  core
  networking
  networking_interfaces
  analytics
  analytics_interfaces
  appsecurity
  appsecurity_interfaces
end

target 'Chip' do
  # Comment the next line if you don't want to use dynamic frameworks
  project 'Modules/Journey/Chip/Chip.xcodeproj'
  use_frameworks!

  core
  networking
  networking_interfaces
  analytics_interfaces
  
end

target 'Home' do
  # Comment the next line if you don't want to use dynamic frameworks
  project 'Modules/Journey/Home/Home.xcodeproj'
  use_frameworks!

  core
  networking_interfaces
  analytics_interfaces
  
end

target 'Login' do
  # Comment the next line if you don't want to use dynamic frameworks
  project 'Modules/Journey/Login/Login.xcodeproj'
  use_frameworks!
  
  core
  networking
  networking_interfaces
  analytics_interfaces
end

target 'Profile' do
  # Comment the next line if you don't want to use dynamic frameworks
  project 'Modules/Journey/Profile/Profile.xcodeproj'
  use_frameworks!
  
  core
  networking_interfaces
  analytics_interfaces
  
end

############## Demonstration Targets ##############

target 'LoginDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  project 'Modules/Journey/Login/Login.xcodeproj'
  use_frameworks!
  
  core
  home
  networking
  networking_interfaces
  analytics
  analytics_interfaces
  login
end
