# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for App
  pod 'Chip', :path => 'Modules/Journey/Chip/Chip.podspec'
  pod 'Networking', :path => 'Modules/Structural/Networking/Networking.podspec'
  pod 'NetworkingInterfaces', :path => 'Modules/Structural/Networking/NetworkingInterfaces/NetworkingInterfaces.podspec'

end
